services:
  # MySQL Database for relational data (Projects, Vendors, Matches)
  mysql-db:
    image: mysql:8.0
    container_name: vendor-matching-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vendor_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: UTC
      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # MongoDB for unstructured research documents
  mongodb:
    image: mongo:6.0
    container_name: vendor-matching-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

# Named volumes to persist data even if containers are removed
volumes:
  mysql_data:
  mongo_data:

# A network allows the containers to communicate with each other if needed
networks:
  app-network:
    driver: bridge

    